/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;

import unit_poli.*;
import farmasi.Crud_farmasi;
import farmasi.Crud_local;
import farmasi.NewJFrame;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import tools.Utilitas;


/**
 *
 * @author jengcool
 */
public class frm_petugas_poli extends javax.swing.JFrame {

    /**
     * Creates new form frm_petugas_poli
     */
    
    private Crud_farmasi dat;
    
    private Crud_local datl;
    
    private boolean editmode;
    
    private void refreshtb(){
     try {
             
             datl=new Crud_local();
             datl.readRec_cariPetugas();
             tb_petugas.setModel(datl.modelpetugas);
             
         } catch (Exception ex) {
             Logger.getLogger(frm_petugas_poli.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    
    public frm_petugas_poli() {
        initComponents();
        
        
        try {
             datl=new Crud_local();
             datl.readRec_cariPoli();
             tb_poli.setModel(datl.modelpoli);
             
         } catch (Exception ex) {
             Logger.getLogger(frm_petugas_poli.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        
        refreshtb();
        
        
        this.setLocationRelativeTo(null);
        
        txt_cari.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
               filterpetugaspoli();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
               filterpetugaspoli();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
               filterpetugaspoli();
            }
        });
        
        txt_cari_poli.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
               filterpoli();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
               filterpoli();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
               filterpoli();
            }
        });
        
        txt_cari_petugas.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
               filterPetugas();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
              filterPetugas();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
              filterPetugas();
            }
        });
        
        
        try {
            dat=new Crud_farmasi();
            dat.readRec_petugas();
            
            this.tb_cari_petugas.setModel(dat.modeltugas);
            
            
        } catch (Exception ex) {
            Logger.getLogger(frm_petugas_poli.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlg_cari_petugas = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_cari_petugas = new javax.swing.JTable();
        txt_cari_petugas = new javax.swing.JTextField();
        dlg_cari_poli = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_poli = new javax.swing.JTable();
        txt_cari_poli = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_pwd = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        lbl_retype = new javax.swing.JLabel();
        txt_pwd2 = new javax.swing.JPasswordField();
        txt_nip = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nama_petugas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lbl_kode_poli = new javax.swing.JTextField();
        bt_cari_nip = new javax.swing.JButton();
        bt_cari_poli = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_poli = new javax.swing.JTextField();
        lbl_retype1 = new javax.swing.JLabel();
        txt_pwd_baru = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        bt_save = new javax.swing.JButton();
        bt_cancel = new javax.swing.JButton();
        bt_add = new javax.swing.JButton();
        bt_edit = new javax.swing.JButton();
        bt_hapus = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_petugas = new javax.swing.JTable();
        txt_cari = new javax.swing.JTextField();
        bt_cari = new javax.swing.JButton();

        dlg_cari_petugas.setModal(true);
        dlg_cari_petugas.setSize(new java.awt.Dimension(451, 381));

        tb_cari_petugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_cari_petugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_cari_petugasMouseReleased(evt);
            }
        });
        tb_cari_petugas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_cari_petugasKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tb_cari_petugas);

        txt_cari_petugas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cari_petugasKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout dlg_cari_petugasLayout = new javax.swing.GroupLayout(dlg_cari_petugas.getContentPane());
        dlg_cari_petugas.getContentPane().setLayout(dlg_cari_petugasLayout);
        dlg_cari_petugasLayout.setHorizontalGroup(
            dlg_cari_petugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg_cari_petugasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlg_cari_petugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addComponent(txt_cari_petugas))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        dlg_cari_petugasLayout.setVerticalGroup(
            dlg_cari_petugasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlg_cari_petugasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_cari_petugas, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        dlg_cari_poli.setModal(true);
        dlg_cari_poli.setSize(new java.awt.Dimension(477, 453));

        tb_poli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_poli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_poliMouseReleased(evt);
            }
        });
        tb_poli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_poliKeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(tb_poli);

        txt_cari_poli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cari_poliKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout dlg_cari_poliLayout = new javax.swing.GroupLayout(dlg_cari_poli.getContentPane());
        dlg_cari_poli.getContentPane().setLayout(dlg_cari_poliLayout);
        dlg_cari_poliLayout.setHorizontalGroup(
            dlg_cari_poliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlg_cari_poliLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dlg_cari_poliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_cari_poli)
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        dlg_cari_poliLayout.setVerticalGroup(
            dlg_cari_poliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlg_cari_poliLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txt_cari_poli, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("User Name");

        txt_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_usernameKeyPressed(evt);
            }
        });

        txt_pwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pwdKeyPressed(evt);
            }
        });

        jLabel3.setText("Password");

        lbl_retype.setText("Retype Password");

        txt_pwd2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pwd2KeyPressed(evt);
            }
        });

        txt_nip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nipKeyPressed(evt);
            }
        });

        jLabel5.setText("Nip");

        jLabel6.setText("Nama Petugas");

        txt_nama_petugas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nama_petugasKeyPressed(evt);
            }
        });

        jLabel7.setText("ID Poli");

        lbl_kode_poli.setEditable(false);
        lbl_kode_poli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbl_kode_poliKeyPressed(evt);
            }
        });

        bt_cari_nip.setText("...");
        bt_cari_nip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cari_nipActionPerformed(evt);
            }
        });

        bt_cari_poli.setText("...");
        bt_cari_poli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cari_poliActionPerformed(evt);
            }
        });

        jLabel8.setText("Nama Poli");

        txt_poli.setEditable(false);
        txt_poli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_poliKeyPressed(evt);
            }
        });

        lbl_retype1.setText("Password Baru");

        txt_pwd_baru.setEditable(false);
        txt_pwd_baru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pwd_baruKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_retype, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_retype1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_pwd2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pwd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_poli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_kode_poli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nama_petugas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pwd_baru, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_cari_nip, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cari_poli, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbl_kode_poli, txt_nama_petugas, txt_nip, txt_poli, txt_pwd, txt_pwd2, txt_pwd_baru, txt_username});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_nip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cari_nip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_nama_petugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_kode_poli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cari_poli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_poli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_retype1)
                    .addComponent(txt_pwd_baru, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_retype)
                    .addComponent(txt_pwd2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_pwd, txt_pwd2, txt_pwd_baru});

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bt_save.setText("Save");
        bt_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_saveActionPerformed(evt);
            }
        });

        bt_cancel.setText("Exit");
        bt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelActionPerformed(evt);
            }
        });

        bt_add.setText("Add");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        bt_edit.setText("Edit");
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editActionPerformed(evt);
            }
        });

        bt_hapus.setText("Hapus");
        bt_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt_save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_hapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cancel)
                    .addComponent(bt_save)
                    .addComponent(bt_add)
                    .addComponent(bt_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tb_petugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_petugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tb_petugasMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tb_petugas);

        bt_cari.setText("cari");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cari)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_cari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usernameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_pwd.requestFocus();
        }
    }//GEN-LAST:event_txt_usernameKeyPressed

    private void txt_pwdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pwdKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_pwd2.requestFocus();
        }
    }//GEN-LAST:event_txt_pwdKeyPressed

    private void txt_pwd2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pwd2KeyPressed
        // TODO add your handling code here:
      if(this.txt_pwd_baru.getText().isEmpty()){  
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bt_save.requestFocus();
        }
      }
      else{
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bt_edit.requestFocus();
        }
      }
    }//GEN-LAST:event_txt_pwd2KeyPressed

    private void txt_nipKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nipKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bt_cari_nip.requestFocus();
        }
    }//GEN-LAST:event_txt_nipKeyPressed

    private void txt_nama_petugasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nama_petugasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_petugasKeyPressed

    private void lbl_kode_poliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_kode_poliKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_kode_poliKeyPressed

    private void savepetugas(){
        try {
            datl=new Crud_local();
            datl.Save_petugas(this.txt_nip.getText(), this.txt_nama_petugas.getText(), 
                    Integer.valueOf(this.lbl_kode_poli.getText()), this.txt_username.getText(), this.txt_pwd.getText());
        } catch (Exception ex) {
            Logger.getLogger(frm_petugas_poli.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    
      private void updatepetugaspass(){
        try {
            datl=new Crud_local();
            datl.Update_petugaspwd(this.txt_nip.getText(), this.txt_nama_petugas.getText(), 
                    Integer.valueOf(this.lbl_kode_poli.getText()), this.txt_username.getText(), this.txt_pwd_baru.getText());
        } catch (Exception ex) {
            Logger.getLogger(frm_petugas_poli.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    
    private void updatepetugas(){
        try {
            datl=new Crud_local();
            datl.Update_petugas(this.txt_nip.getText(), this.txt_nama_petugas.getText(), 
                    Integer.valueOf(this.lbl_kode_poli.getText()), this.txt_username.getText());
        } catch (Exception ex) {
            Logger.getLogger(frm_petugas_poli.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    
    private void bt_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_saveActionPerformed

        if(txt_nip.getText().isEmpty()||this.lbl_kode_poli.getText().isEmpty()||this.txt_username.getText().isEmpty()||this.txt_pwd.getText().isEmpty()||this.txt_pwd2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Inputan Kosong!");
            this.txt_username.requestFocus();
        }
        else{
            if(this.txt_pwd2.getText().equals(this.txt_pwd.getText())){
                
                this.savepetugas();
                this.refreshtb();
                txtcls();
            }
            else{
                this.txt_pwd2.requestFocus();
                JOptionPane.showMessageDialog(null, "Password Tidak sama!");

            }
        }
    }//GEN-LAST:event_bt_saveActionPerformed

    private void bt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bt_cancelActionPerformed

    private void txtcls(){
    txt_pwd_baru.setEditable(false);
        Utilitas.HapusText(jPanel1);
        txt_pwd_baru.setText("");
        txt_pwd.setText("");
        txt_pwd2.setText("");
    }
    
    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        // TODO add your handling code here:
        txtcls();
    }//GEN-LAST:event_bt_addActionPerformed

    private void bt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editActionPerformed
        // TODO add your handling code here:
         if(txt_nip.getText().isEmpty()||this.lbl_kode_poli.getText().isEmpty()||this.txt_username.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Inputan Kosong!");
            this.txt_username.requestFocus();
        }
        else{
          
          if(!txt_pwd_baru.getText().isEmpty()) {  
            if(this.txt_pwd2.getText().equals(this.txt_pwd_baru.getText())){
                
                loginActPetugas();
               
                this.refreshtb();
            }
            else{
                this.txt_pwd2.requestFocus();
                JOptionPane.showMessageDialog(null, "Password Tidak sama!");

            }
          }
          else{
               this.updatepetugas();
               this.refreshtb();
          } 
        }
    }//GEN-LAST:event_bt_editActionPerformed

    private void hapuspetugas(){
        try {
            datl=new Crud_local();
            datl.DelRecPetugas(this.txt_nip.getText());
            
        } catch (Exception ex) {
            Logger.getLogger(frm_petugas_poli.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }
    
    private void bt_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hapusActionPerformed
        // TODO add your handling code here:
     if(!txt_nip.getText().isEmpty())   {
         int dialogResult = JOptionPane.showConfirmDialog(null, "Apakah Akan di Hapus?","Warning ",
   JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
   
     if(dialogResult == JOptionPane.YES_OPTION){  
        hapuspetugas();
        this.refreshtb();
      }
     }
     else{
         JOptionPane.showMessageDialog(null, "Maaf Nip Kosong Tidak Bisa di Hapus!");
     }
    }//GEN-LAST:event_bt_hapusActionPerformed

    private void tb_poliMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_poliMouseReleased
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int row = this.tb_poli.getSelectedRow();

            if (row == -1) {
                // No row selected
            } else {
                lbl_kode_poli.setText(this.tb_poli.getModel().getValueAt(row, 0).toString());
                this.txt_poli.setText(this.tb_poli.getModel().getValueAt(row, 1).toString());
                this.dlg_cari_poli.setVisible(false);
                
                this.txt_username.requestFocus();
            }
        }
    }//GEN-LAST:event_tb_poliMouseReleased

    private void tb_poliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_poliKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int row = this.tb_poli.getSelectedRow();

            if (row == -1) {
                // No row selected
            } else {

                lbl_kode_poli.setText(this.tb_poli.getModel().getValueAt(row, 0).toString());
                this.txt_poli.setText(this.tb_poli.getModel().getValueAt(row, 1).toString());
                this.dlg_cari_poli.setVisible(false);

                //txt_tarif.requestFocus();
                this.txt_username.requestFocus();
            }

        }
    }//GEN-LAST:event_tb_poliKeyPressed

    private void txt_cari_poliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cari_poliKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tb_poli.requestFocus();
            tb_poli.setRowSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_txt_cari_poliKeyPressed

    private void txt_poliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_poliKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_poliKeyPressed

    private void bt_cari_nipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cari_nipActionPerformed
        // TODO add your handling code here:
        dlg_cari_petugas.setLocationRelativeTo(this);
        dlg_cari_petugas.setVisible(true);
        
    }//GEN-LAST:event_bt_cari_nipActionPerformed

    private void txt_cari_petugasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cari_petugasKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             tb_cari_petugas.requestFocus();
             tb_cari_petugas.setRowSelectionInterval(0, 0);
         }
    }//GEN-LAST:event_txt_cari_petugasKeyPressed

    private void bt_cari_poliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cari_poliActionPerformed
        // TODO add your handling code here:
        this.dlg_cari_poli.setLocationRelativeTo(this);
        this.dlg_cari_poli.setVisible(true);
    }//GEN-LAST:event_bt_cari_poliActionPerformed

    private void tb_cari_petugasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_cari_petugasKeyPressed
        // TODO add your handling code here:
          // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int row = this.tb_cari_petugas.getSelectedRow();

            if (row == -1) {
                // No row selected
            } else {

                txt_nip.setText(this.tb_cari_petugas.getModel().getValueAt(row, 0).toString());
                this.txt_nama_petugas.setText(this.tb_cari_petugas.getModel().getValueAt(row, 1).toString());
                this.dlg_cari_petugas.setVisible(false);

                bt_cari_poli.requestFocus();

            }

        }
        
    }//GEN-LAST:event_tb_cari_petugasKeyPressed

    private void tb_cari_petugasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_cari_petugasMouseReleased
        // TODO add your handling code here:
         if (evt.getClickCount() == 2) {
            int row = this.tb_cari_petugas.getSelectedRow();

            if (row == -1) {
                // No row selected
            } else {
                txt_nip.setText(this.tb_cari_petugas.getModel().getValueAt(row, 0).toString());
                this.txt_nama_petugas.setText(this.tb_cari_petugas.getModel().getValueAt(row, 1).toString());
                this.dlg_cari_petugas.setVisible(false);
            }
        }
    }//GEN-LAST:event_tb_cari_petugasMouseReleased

    private void tb_petugasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_petugasMouseReleased
        // TODO add your handling code here:
          // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int row = this.tb_petugas.getSelectedRow();

            if (row == -1) {
                // No row selected
            } else {
                
                this.txt_nip.setText(this.tb_petugas.getModel().getValueAt(row, 0).toString());
                this.txt_nama_petugas.setText(this.tb_petugas.getModel().getValueAt(row, 1).toString());
                lbl_kode_poli.setText(this.tb_petugas.getModel().getValueAt(row, 2).toString());
                this.txt_poli.setText(this.tb_petugas.getModel().getValueAt(row, 3).toString());
                this.txt_username.setText(this.tb_petugas.getModel().getValueAt(row, 4).toString());
                this.txt_nip.requestFocus();
                txt_pwd_baru.setEditable(true);
            }
        }
    }//GEN-LAST:event_tb_petugasMouseReleased

    private void txt_pwd_baruKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pwd_baruKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_pwd2.requestFocus();
        }
    }//GEN-LAST:event_txt_pwd_baruKeyPressed

        
   private void filterpetugaspoli(){
    
          try {
                datl = new Crud_local();

                try {
                    datl.readRec_cariPetugasF(txt_cari.getText());
                } catch (SQLException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                tb_petugas.setModel(datl.modelpetugas);
            } catch (Exception ex) {
                Logger.getLogger(frm_petugas_poli.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
         
        
    private void filterpoli(){
    
          try {
                datl = new Crud_local();

                try {
                    datl.readRec_cariPoli(txt_cari_poli.getText());
                } catch (SQLException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                tb_poli.setModel(datl.modelpoli);
            } catch (Exception ex) {
                Logger.getLogger(frm_petugas_poli.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
     private void filterPetugas(){
    
          try {
                dat = new Crud_farmasi();

                try {
                    dat.readRec_petugasF(txt_cari_petugas.getText());
                } catch (SQLException ex) {
                    Logger.getLogger(frm_petugas_poli.class.getName()).log(Level.SEVERE, null, ex);
                }

                tb_cari_petugas.setModel(dat.modeltugas);
            } catch (Exception ex) {
                Logger.getLogger(frm_petugas_poli.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
     
     
     private void loginActPetugas(){
   
     
        try {
            datl = new Crud_local();
       
            datl.CekPetugas(txt_username.getText());
            
        } catch (SQLException ex) {
            Logger.getLogger(frm_petugas_poli.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (Exception ex) {
            Logger.getLogger(frm_petugas_poli.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            
            if (Crud_local.usm.equals(txt_username.getText()) && Crud_local.psm.equals(txt_pwd.getText())) {
                   
                  updatepetugaspass();
                
            } else {
                JOptionPane.showMessageDialog(null, "Password Salah Maaf Tidak bisa Edit!");
            }
            
  
     }
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_petugas_poli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_petugas_poli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_petugas_poli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_petugas_poli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_petugas_poli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_cari;
    private javax.swing.JButton bt_cari_nip;
    private javax.swing.JButton bt_cari_poli;
    private javax.swing.JButton bt_edit;
    private javax.swing.JButton bt_hapus;
    private javax.swing.JButton bt_save;
    private javax.swing.JDialog dlg_cari_petugas;
    private javax.swing.JDialog dlg_cari_poli;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField lbl_kode_poli;
    private javax.swing.JLabel lbl_retype;
    private javax.swing.JLabel lbl_retype1;
    private javax.swing.JTable tb_cari_petugas;
    private javax.swing.JTable tb_petugas;
    private javax.swing.JTable tb_poli;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_cari_petugas;
    private javax.swing.JTextField txt_cari_poli;
    private javax.swing.JTextField txt_nama_petugas;
    private javax.swing.JTextField txt_nip;
    private javax.swing.JTextField txt_poli;
    private javax.swing.JPasswordField txt_pwd;
    private javax.swing.JPasswordField txt_pwd2;
    private javax.swing.JPasswordField txt_pwd_baru;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
